### ISSUE TITLE
Load spawn area chunks on start-up

### ISSUE THREAD

**Issue by momothereal** [caelunshun/feather#107]
In order to speed up the initial player join, chunks surrounding the level's spawn coordinates should be loaded in memory at start-up. It would leverage [chunkworker](https://github.com/caelunshun/feather/blob/9b57afcd2ccee8fd0c6eefa27df6f6ac4f28b51a/server/src/chunkworker.rs#L120) and likely be called in the [level initialization](https://github.com/caelunshun/feather/blob/9b57afcd2ccee8fd0c6eefa27df6f6ac4f28b51a/server/src/main.rs#L207).

**Comment by caelunshun** [comment]
A likely solution is to register an `Entity` representing the server and then add a chunk hold on spawn chunks for that entity. This will prevent the chunks from being unloaded.

Something like this:
```rust
let server_entity = world.create_entity().build();
let mut chunk_holders = world.fetch_mut::<ChunkHolders>();

let view_distance = i32::from(world.fetch::<Arc<Config>>().server.view_distance);
for x in -view_distance..=view_distance {
    for z in -view_distance..=view_distance {
        let chunk = ChunkPosition::new(x, z);
        load_chunk(chunk); // Not sure if this is the actual function, but I think something like this exists.
        chunk_holders.add_for_chunk(chunk, server_entity);
    }
}
```

**Comment by caelunshun** [comment]
> In order to speed up the initial player join

Although it's not like joining takes all that long, at least in release mode. The main overhead for join times is chunk sending, not loading, according to my profile tests.
