### ISSUE TITLE
Crash server/time out yourself with chat message

### ISSUE THREAD

**Issue by XantiumNZ** [caelunshun/feather#110]
**Reproduction**
Chat message "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA". That's it.

Doing this too many times crashes the server, but usually just times you out. This doesn't happen server side however, so this can lead to some quirky side effects.

![image](https://user-images.githubusercontent.com/24442053/64215707-10ccf180-cf0a-11e9-9e97-5cf41a21dac9.png)

According to my buddy Lolt every time this happens one core crashes. When the server runs out of cores, the entire server crashes. Sending the chat message then reconnecting on a 6 core server crashed on the 6th attempt.

**Comment by caelunshun** [comment]
Seems like the cutoff is at any message of length 253 characters. I suspect this is an issue with handling of compressed packets received from the client.

**Comment by caelunshun** [comment]
Confirmed that this does not occur when compression is disabled (compression_threshold set to -1 in config).

**Comment by caelunshun** [comment]
Thanks for reporting!

**Comment by XantiumNZ** [comment]
No worries!

A bit off topic, would you like survival related bug reports (not the usual I break blocks and get nothing) or would you rather wait until an actual release?

**Comment by caelunshun** [comment]
> No worries!
> 
> A bit off topic, would you like survival related bug reports (not the usual I break blocks and get nothing) or would you rather wait until an actual release?

Nothing in survival mode is really implemented, but you can reply to #40 with anything you find.
