### ISSUE TITLE
Stack unstackable items and stackable items past 64

### ISSUE THREAD

**Issue by XantiumNZ** [caelunshun/feather#111]
**Reproduction**
Throw two of the same unstackable item on the ground and pick it up. You will get a stack of 2.

Throw a stack of 64 and a single item of a stackable item on the ground and pick it up. You will get a stack of 65.

If you attempt to pickup a stack higher than 127, it will disappear. Minecraft can only handle stacks below 128.

Video guide: https://www.youtube.com/watch?v=OHPk7LSOlrc

**Comment by caelunshun** [comment]
Yes, item collection is a bit messed up at the moment. I'll get to fixing this later tonight.
