### ISSUE TITLE
Discussion?

### ISSUE THREAD

**Issue by cheako** [caelunshun/feather#112]
Where are ppl hanging out?  There is no mention of where to  go for help or to share your server's info.

**Comment by caelunshun** [comment]
Feather isn't really ready for production yet—it still lacks a ton of features. You're welcome to ask for help here though :)

**Comment by nate-moo** [comment]
how do i know the server is running?

**Comment by caelunshun** [comment]
We've created a Discord server [here](https://discord.gg/4eYmK69).
