### ISSUE TITLE
Update specs dependency to latest master/release

### ISSUE THREAD

**Issue by momothereal** [caelunshun/feather#113]
The specs branch that was used has been [merged](https://github.com/slide-rs/specs/pull/613) a few hours ago, and the author deleted their branch. This dependency will have to be updated, perhaps to the specific [commit](https://github.com/slide-rs/specs/commit/48fa4f0a8c21c44b406f6498322cfbbdd79c3ea8) until the crate is published:

https://github.com/caelunshun/feather/blob/5a397a4f86809d6115aa3365b010a7ebb709d0c1/server/Cargo.toml#L30-L33

**Comment by caelunshun** [comment]
Resolved by #114.
