### ISSUE TITLE
Crossbeam channels

### ISSUE THREAD

**Issue by kazimuth** [caelunshun/feather#115]
This project seems really neat! I was just skimming the source code and I noticed that some places in the code are using `Mutex<Vec<T>>` or `Mutex<Sender/Receiver<T>>`. In particular, the central message bus ([`PacketQueue`](https://github.com/caelunshun/feather/blob/c2ec5b6baaf23f56272ec168998b819f9e006154/server/src/network.rs#L23-L25)) sees to be a `Mutex<Vec<Vec<(Entity, Box<dyn Packet>)>>>`.

I think multiple systems access that queue concurrently, so you'll end up with a lot of contention on that one mutex. You might want to consider using [`crossbeam`](https://crates.io/crates/crossbeam_channel) instead; it offers high-performance MPMC queues / channels that can be used without locking.

You could also using [`strum`](https://crates.io/crates/strum)'s `#[derive(EnumCount)]` on 
the [`PacketType` enum](https://github.com/caelunshun/feather/blob/c2ec5b6baaf23f56272ec168998b819f9e006154/core/src/network/packet/mod.rs#L40-L204) to statically determine the number of packet types your system uses. Then you can pre-size the outer `Vec` in `PacketQueue`, ending up with:

```rust
use strum::EnumCount;
use feather_core::network::packet::PacketType;

struct PacketQueue {
    // could also use ArrayQueue to boost performance further
    queue: Vec<crossbeam::SegQueue<(Entity, Box<dyn Packet>)>
}

impl Default for PacketQueue {
     fn default() -> Self {
         PacketQueue {
              // ordinal of first packet type is 1, so we need 1 extra slot
              queue: (0..PacketType::count()+1).map(|_| crossbeam::SeqQueue::new()).collect()
         }
     }
}
// ...other stuff...
```

This would significantly reduce contention on your central message bus and could give good speedups across the codebase; there'd need to be benchmarks to measure for sure tho.

**Comment by caelunshun** [comment]
Note that the places where `Mutex<Sender>` and `Mutex<Receiver>` are used (in `NetworkComponent`) cannot be changed to use `crossbeam`, since they require an `mio::Poll` implementation. The `mio` bridge for channels is provided by `mio-extras`, which uses `std::sync::mpsc` internally.

**Comment by kazimuth** [comment]
It prolly wouldn't be too hard to reimplement that either, you could basically just find-replace in the mio source: https://github.com/dimbleby/mio-extras/blob/master/src/channel.rs

**Comment by kazimuth** [comment]
:tada:
