### ISSUE TITLE
specs git removed their branch, breaking master build.

### ISSUE THREAD

**Issue by cheako** [caelunshun/feather#130]
Edit: I switched to specs git batch and it looks to be working, what specifically do I need to test?
https://github.com/cheako/feather/commit/c1336cd2f53a972a72cf316e63152848ef64a159

**Comment by caelunshun** [comment]
A fix was committed to develop but hasn't been merged into master.

**Comment by caelunshun** [comment]
Merged the fix into master. 70cc327
