### ISSUE TITLE
Investigate an alternative solution to entity spawning

### ISSUE THREAD

**Issue by caelunshun** [caelunshun/feather#132]
The current lazy model of entity spawning is bug-prone and very difficult to debug. A new way to spawn entities (and do other component access-intensive tasks) needs to be designed which does not cause all sorts of race conditions due to system execution order.

With the current model, I have observed quite a few panics already caused by the lazy entity spawning system, so a change needs to be made.

**Comment by momothereal** [comment]
> With the current model, I have observed quite a few panics already caused by the lazy entity spawning system, so a change needs to be made.

I haven't personally noticed this, is there a specific type of entity that would cause this?

I could see how the `EntitySendSystem` might be part of this, since it'll eventually depend on a lot of entity components to send the proper `SpawnObject` data field. The `FallingBlockComponent` import is an example of this.

**Comment by caelunshun** [comment]
> I haven't personally noticed this, is there a specific type of entity that would cause this?

A while back, I believed I had a panic that went as follows:
* `EntityChunkLoadSystem` requests an entity creation from the world save.
* `SpawnerSystem` creates the entity. It requests that `EntitySendSystem` broadcasts the entity through triggering an entity spawn event.
* The entity is deleted, probably for going into an unloaded chunk.
*  The current tick ends, and the deleted entity is removed.
* In the next tick, `EntitySendSystem` attempts to send the entity, but it panics when unwrapping the retrieved components for the entity, which no longer exists.

This can be mitigated by checking if the entity is still alive in `EntitySendSystem`, but I feel that a lot more of this type of issue will pop up. And note that these problems are very hard to debug—stack traces are useless, since you can't know which system requested a lazy entity spawn, so you have to resort to all sorts of nasty print debugging.
