### ISSUE TITLE
Incorrect stack sizes not yet fixed in 0.5

### ISSUE THREAD

**Issue by XantiumNZ** [caelunshun/feather#158]
From my experimentation, these are the incorrect stack sizes I've found.

**Items that stack too high on server**

- Snowballs should max at 16
- Banners should max at 16
- Signs should max at 16
- Armor stands should max at 16
- Eggs should max at 16

**Unstackable items that are stackable on server**

- Beds
- Shulker boxes
- Turtle shells
- Fishing rods
- Enchanted books
- Potions and water bottles (which turn into uncraftable potions on drop)
- Filled buckets, including fish and liquid
- Carrot on a stick
- Elytra
- Shield
- Trident
- Music discs
- Totem of undying
- Shears
- Boat
- Mushroom stew
- Beetroot soup
- Rabbit stew
- Cake
- All types of minecarts
- Horse armor

There may be more not listed.

**Comment by caelunshun** [comment]
Thanks for the thorough list! I'll add these to the function and get back to you.

**Comment by caelunshun** [comment]
I've added the items in your list—feel free to let me know if there's more missing.
