### ISSUE TITLE
Support block placement

### ISSUE THREAD

**Issue by caelunshun** [caelunshun/feather#46]

**Comment by caelunshun** [comment]
The most laborious part of this is that the item generator needs to generate mappings from items to blocks such that the block corresponding to an item can be found. Since, in the future, we all also have to add mappings the other way around (to handle survival mode digging), I envision adding another crate, named `feather_block_item`, which links together the block and item crates. This would avoid a cyclic dependency between `feather_blocks` and `feather_items`.

**Comment by momothereal** [comment]
I noticed that the handling of the Creative Item packet doesn't take into account the "raw slot" logic:

**Comment by caelunshun** [comment]
Yes, I see what you mean. Inventory slot indices are currently numbered as per https://wiki.vg/Inventory#Player_Inventory, which is only valid for the normal inventory—not for when e.g. the player is interacting with a crafting table (although those aren't implemented, so I haven't observed the problem).

I'm not sure of the ideal way to fix this in a Rust-like way. Perhaps we could use an enum type with a variant for each possible slot and then map those variants to raw slot IDs depending on the inventory type.

I'm going to move this into #79, since it's a separate issue from block placement.

**Comment by caelunshun** [comment]
Block placement is now implemented.

#79 and #84 remain as issues related to it, but both are unnoticeable with the current feature set (inventories other than the player inventory menu are unimplemented, and water/lava physics don't exist yet).

I will move discussion to those respective issues and close this.
